# Site settings
title: Seoul AI - Hackaton
description: Amazing website for an amazing event
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hackaton
user_description: Group of professionals from different fields meets twice per month in the heart of Seoul to discuss about AI or implement various AI applications.
user_title: Seoul AI
email:
twitter_username: SeoulAI
github_username:  SeoulAI
facebook_username:  Seoul AI

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
