title: Seoul Artificial Intelligence
description: Group of professionals from different fields meet twice per month in the heart of Seoul to discuss about AI or implement various AI applications.
google_analytics: UA-106993341-1
theme: jekyll-theme-minimal
url: http://seoulai.com
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
