title: Seoul Artificial Intelligence Meetup
description: Group of professionals from different fields meet twice per month in the heart of Seoul to discuss about AI or implement various AI applications.
google_analytics: UA-106993341-1
theme: jekyll-theme-minimal
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
