title: Seoul Artificial Intelligence Meetup
description: Group of experts from different fields meet twice per month in heart of Seoul to discuss or implement various AI applications.
google_analytics: UA-106993341-1
theme: jekyll-theme-minimal
plugins:
    - jekyll-sitemap
