# Site settings
title: Seoul Artificial Intelligence
description: Seoul AI is the largest international Artificial Intelligence community in Seoul. Group of professionals from different fields meets twice per month in the heart of Seoul to discuss about AI or implement various AI applications.

# User settings
user_description: Group of professionals from different fields meets twice per month in the heart of Seoul to discuss about AI or implement various AI applications.
url: http://seoulai.com
highlighter: rouge
google_analytics: UA-106993341-1
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag

exclude: ['package.json', 'src' , 'node_modules']
